name: Nerfstick
version: '${version}'
main: com.arekkuzzera.nerfstick.Nerfstick
api-version: "1.21"
authors: [ AREKKUZZERA ]
description: >
  A modern Paper plugin that adds fine-grained control over the vanilla Debug Stick.
  Allows safe usage in survival while restricting block state editing in protected regions
  and configurable per-block permissions.
